# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KX--CoiR60n71t7WaLyNIoWhQlAFivXl
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
documents = [
    "Python is a popular programming language",
    "Machine learning uses algorithms to learn from data",
    "Python is widely used for machine learning",
    "Natural language processing is a field of artificial intelligence",
    "Deep learning is used in artificial intelligence"
]
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)
query = input("Enter your search query: ")
query_vector = vectorizer.transform([query])
similarity_scores = cosine_similarity(
    query_vector,
    tfidf_matrix
).flatten()
ranked_documents = similarity_scores.argsort()[::-1]
print("\nSearch Results:\n")
for index in ranked_documents:
    print("Document:", documents[index])
    print("Similarity Score:", round(similarity_scores[index], 3))
    print()